import carousal_img1 from '../../assets/banner/car-1.png';
import carousal_img2 from '../../assets/banner/car-2.png';
import carousal_img3 from '../../assets/banner/car-3.png';
import carousal_img4 from '../../assets/banner/car-4.png';

import category_img1 from '../../assets/banner/category_img1.png';
import category_img2 from '../../assets/banner/category_img2.png';
import category_img3 from '../../assets/banner/category_img3.png';


export const products = [
  {
    id: 1,
    brand : 'Marshell',
    title: "Royal Design Handmade Soapbox",
    description: "High-quality canvas shoes.",
    price: "2012",
    discounted: "1556",
    currency: "₹",
    categoryName : "Home & Decor",
    product_code : "ASD4565SS562",
    image: "https://rb.gy/yqvcsh",
    rating : "3",
  },
  {
    id: 2,
    brand : 'Marshell',
    title: "royal wine set",
    description: "This handcrafted rajasthani royal wine pattern is made of pure brass.",
    price: "2556",
    currency: "₹",
    categoryName : "Lamps & Chandelier",
    discounted: "1556",
    product_code : "ASD4565SS562",
    image: "https://rb.gy/d4bd0m",
    rating : "4",
  },
  {
    id: 3,
    brand : 'Marshell',
    title: "Royal gifting box",
    description: "Pure 925 sterling silver handmade nakashi /naxi work dry fruit box,",
    currency: "₹",
    categoryName : "Lamps & Chandelier",
    price: "3000",
    product_code : "ASD4565SS562",
    image: "https://rb.gy/px7svm",
    rating : "4.5",
  },
  {
    id: 4,
    brand : 'Marshell',
    title: "royal wine set",
    description: "This handcrafted rajasthani royal wine set in antique pattern is made.",
    price: "25566",
    currency: "₹",
    categoryName : "Lamps & Chandelier",
    discounted: "15569",
    product_code : "ASD4565SS562",
    image: "https://rb.gy/d4bd0m",
    rating : "3.5",
  },
  {
    id: 5,
    brand : 'Marshell',
    title: "Royal Antique Choker Necklace",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Lamps & Chandelier",
    image: "https://shorturl.at/htFMW",
    rating : "4",
  },
  {
    id: 6,
    brand : 'Kottanz',
    title: "Metal Lantern Lamp Set of 3",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: "1499.00",
    discounted: 1099.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Lamps & Chandelier",
    image: "https://shorturl.at/erBQ8",
    rating : "4",
  },
  {
    id: 7,
    brand : 'Marshell',
    title: "Handmade Wooden Lamp",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "Illuminate your living space with the warm and inviting glow of our Handmade Wooden Beautiful Lamp.",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Furniture & Carpets",
    image: "https://shorturl.at/vxG68",
    rating : "4",
  },
  {
    id: 8,
    brand : 'Marshell',
    title: "Sacred Lord Ganesha Ceramic Idol",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 999,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Furniture & Carpets",
    image: "https://shorturl.at/suyYZ",
    rating : "4",
  },
  {
    id: 9,
    brand : 'Marshell',
    title: "Royal Antique Choker Necklace",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Furniture & Carpets",
    image: "https://shorturl.at/htFMW",
    rating : "4",
  },
  {
    id: 10,
    brand : 'Marshell',
    title: "Royal Antique Choker Necklace",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Furniture & Carpets",
    image: "https://shorturl.at/htFMW",
    rating : "4",
  },
  {
    id: 11,
    brand : 'Marshell',
    title: "Royal Antique Choker Necklace",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Furniture & Carpets",
    image: "https://shorturl.at/htFMW",
    rating : "4",
  },
  {
    id: 12,
    brand : 'Marshell',
    title: "Royal Antique Choker Necklace",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Home & Decor",
    image: "https://shorturl.at/htFMW",
    rating : "4",
  },
  {
    id: 13,
    brand : 'Marshell',
    title: "Royal Antique Choker Necklace",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Furniture & Carpets",
    image: "https://shorturl.at/htFMW",
    rating : "4",
  },
  {
    id: 14,
    brand : 'Marshell',
    title: "Royal Antique Choker Necklace",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Furniture & Carpets",
    image: "https://shorturl.at/htFMW",
    rating : "4",
  },
  {
    id: 15,
    brand : 'Marshell',
    title: "Royal Antique Choker Necklace",
    description: "A 22KT yellow gold traditional necklace (30.61 gms).",
    description2 : "A 22KT yellow gold traditional necklace (30.61 gms). A delightful blend of ethnic and contemporary, this necklace will complement any look! (Without Back Chain)",
    price: 217592.00,
    product_code : "ASD4565SS562",
    currency: "₹",
    categoryName : "Home & Decor",
    image: "https://shorturl.at/htFMW",
    rating : "4",
  },
]

export const carousel = [
  {
    id : 1,
    image : carousal_img1,
  },
  {
    id : 1,
    image : carousal_img2,
  },
  {
    id : 1,
    image : carousal_img3,
  },
  {
    id : 1,
    image : carousal_img4,
  },
]

export const categories = [
  {
    id : 1,
    categoryName : "Home & Decor",
    image : category_img3,
  },
  {
    id : 2,
    categoryName : "Lamps & Chandelier",
    image : category_img2,
  },
  {
    id : 3,
    categoryName : "Furniture & Carpets",
    image : category_img1,
  },
]
